### ISSUE TITLE
Parsing NSX file error

### ISSUE THREAD

**Issue by Antergosgeek** [andreas-vester/notestation-to-joplin#3]
Starts out fine but after reading a couple of notes I get the following error:
`Traceback (most recent call last):
  File "nsx2joplin.py", line 459, in <module>
    nsx_content = nsx.extract_data_from_nsx(nsx_file=nsx_file, save_pickle=False)
  File "nsx2joplin.py", line 249, in extract_data_from_nsx
    for attachment in note_data["attachment"]:
TypeError: 'NoneType' object is not iterable`

Unfortunately since I am not a huge programmer and not very experienced with python I don’t know how to fix this. Can you provide help? I would really like to move to Joplin but can’t do it if I can’t get this to work. I tried Note station to Markdown but that breaks all attachment links for me and isn’t really an option.

**Comment by Antergosgeek** [comment]
No one?

**Comment by chenzhutao** [comment]
I found the same problem and don't know how to fix it.

**Comment by exfounder** [comment]
I found the same problem and do not know how can I fix it.

**Comment by paluigi** [comment]
I fixed this error by changing line 247 and checking if `node_data["attachment"] `is `None` in the following way:
`if "attachment" in note_data and note_data["attachment"] is not None:`

Note that I have another error afterwards (the same as #1  ), so this fix only bring me that far...
